[profile.default]
test = 'test/solidity'
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 10000
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea73'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea73'
fs_permissions = [{ access = "read", path = "./deployments/"},{ access = "read", path = "./config/"}]

[rpc_endpoints]
mainnet = "${ETH_NODE_URI_MAINNET}"
polygon = "${ETH_NODE_URI_POLYGON}"
bsc = "${ETH_NODE_URI_BSC}"
gnosis = "${ETH_NODE_URI_GNOSIS}"
fantom = "${ETH_NODE_URI_FANTOM}"
okx = "${ETH_NODE_URI_OKX}"
avalanche = "${ETH_NODE_URI_AVALANCHE}"
arbitrum = "${ETH_NODE_URI_ARBITRUM}"
optimism = "${ETH_NODE_URI_OPTIMISM}"
moonriver = "${ETH_NODE_URI_MOONRIVER}"
moonbeam = "${ETH_NODE_URI_MOONBEAM}"
celo = "${ETH_NODE_URI_CELO}"
fuse = "${ETH_NODE_URI_FUSE}"
cronos = "${ETH_NODE_URI_CRONOS}"
velas = "${ETH_NODE_URI_VELAS}"
harmony = "${ETH_NODE_URI_HARMONY}"
evmos = "${ETH_NODE_URI_EVMOS}"
aurora = "${ETH_NODE_URI_AURORA}"
boba = "${ETH_NODE_URI_BOBA}"

# testnets
goerli = "${ETH_NODE_URI_GOERLI}"
sepolia = "${ETH_NODE_URI_SEPOLIA}"

[etherscan]
mainnet = {key = "${ETHERSCAN_KEY}"}
polygon = {key = "${POLYGON_ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api"}
bsc = {key = "${BSCSCAN_KEY}", url = "https://api.bscscan.com/api"}
gnosis = {key = "${GNOSISBSCOUT_KEY}", url = "https://blockscout.com/poa/xdai/api"}
fantom = {key = "${FTMSCAN_KEY}", url = "https://api.ftmscan.com/api"}
avalanche = {key = "${SNOWTRACE_KEY}", url = "https://api.snowtrace.io/api"}
arbitrum = {key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api"}
optimism = {key = "${OPTIMISM_ETHERSCAN_KEY}", url = "https://api-optimistic.etherscan.io/api"}
moonriver = {key = "${MOONRIVER_MOONSCAN_KEY}", url = "https://api-moonriver.moonscan.io/api"}
moonbeam = {key = "${MOONBEAM_MOONSCAN_KEY}", url = "https://api-moonbeam.moonscan.io/api"}

#testnets
goerli = {key = "${ETHERSCAN_KEY}"}
sepolia = {key = "${ETHERSCAN_KEY}"}
